version: '3'
services:
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb"
    volumes:
      - dynamodb_data:/dynamodblocal
  shop-backoffice:
    build:
      context: ./shop-backoffice
      dockerfile: Dockerfile
    ports:
      - "8081:8081"

volumes:
  dynamodb_data: