
POST http://localhost:8081/backoffice/products
Content-Type: application/json
correlationId: "30eb2105-f4cc-49e0-95e8-04da1eca3737"
traceId: "30eb2105"
flowId: "99882992"

{
    "nome": "Novo Produto",
    "departamento": "Informatica",
    "tags": ["Informatica","Notebook","Acessorios","Home-Office", "Promocao"],
    "preco": 1500000,
    "quantidade": 200,
    "ativo": true
}

###
GET http://localhost:8081/backoffice/health/status
