POST http://localhost:8081/backoffice/products
Content-Type: application/json
correlationId: "30eb2105-f4cc-49e0-95e8-04da1eca3737"
traceId: "30eb2105"

{
    "nome": "ACER 23",
    "departamento": "Informatica",
    "tags": ["Informatica","Notebook","Acessorios","Home-Office"],
    "preco": 1200000,
    "quantidade": 3,
    "ativo": true
}

###

GET http://localhost:8081/backoffice/health/status
