POST http://localhost:8081/backoffice/products
Content-Type: application/json

{
    "nome": "ACER 23",
    "departamento": "Informatica",
    "tags": ["Informatica","Notebook","Acessorios","Home-Office"],
    "preco": 1200000,
    "quantidade": 3,
    "ativo": true
}

###

GET http://localhost:8081/backoffice/health/status
